### ISSUE TITLE
Code Issue

### ISSUE THREAD

**Issue by SankalpMe** [JonComo/anim#15] opened 2021-01-19 12:36 UTC
Could I partion the code / use webpack to make the code cleaner and easy to maintain.

**Comment by JonComo** [comment] 2021-01-26 03:09
Definitely! I would love that.

**Comment by catruge** [comment] 2021-02-21 13:10
Hello. Do you think that I could help @SankalpMe with setting up Webpack?

**Comment by SankalpMe** [comment] 2021-02-22 11:40
@ca

> Hello. Do you think that I could help @SankalpMe with setting up Webpack? It would be easier to test new code out since its hot reload capabilities would be available. A package manager like NPM would also make it a bit easier to use `jquery`, `numeric`, `math.js` and so on without including their actual code in this repository (and in most cases a package manager would be used either way to install Webpack).


Sure , right now I am busy with work , but would really love to get started.

**Comment by catruge** [comment] 2021-02-22 16:21
> Sure , right now I am busy with work , but would really love to get started.

Thanks, @SankalpMe! I don't have very much experience with collaborating on GitHub. Should we create a fork of this repository to be able to set up Webpack?

**Comment by catruge** [comment] 2021-02-24 21:19
@SankalpMe, I created a GitHub organization, forked this repository and added you as a maintainer (the repository is available at https://github.com/supreme-pancakes/anim). If you have a better idea, then we can try that instead. I think I will start setting up Webpack in the fork for now and will create an issue for discussion.

**Comment by JonComo** [comment] 2021-02-26 03:20
@SankalpMe @catruge This is amazing, thank you so much for continuing this project! Let me know how I can be of support. I don't have time to do much coding but if you need me to turn a setting on or off or something like that just ping me.

**Comment by catruge** [comment] 2021-02-26 17:15
@JonComo, thank you! I set up Wepback and ESLint and it appears to be working, but some tweaks are necessary to the code; there seems to be a problem with the implicitly-declared global variables that are used in `main.js` since Webpack makes everything run in strict mode, but I was able to find most of them (I think). I'm checking to see if ESLint might have an option to report them and I think I found the right way to do it. I did want to ask about `CCapture.js` and `numeric.js`. I couldn't find them used at all except for the `CCapture` class in the `Animator` class, but didn't see the `Animator` class being used anywhere. Also, the `math.rotate` function is already defined when using the `mathjs` package. I think that the one that is defined in `main.js` rotates the camera. Could I rename it to `rotateCamera` to prevent it from conflicting? Thanks again.

**Comment by SankalpMe** [comment] 2021-02-27 11:31
@catruge  just free from work let me have a look around from what you have done , will start from tomorrow.

**Comment by catruge** [comment] 2021-02-27 12:42
@SankalpMe, thanks so much for doing that!

**Comment by JonComo** [comment] 2021-02-28 03:33
@catruge So now how can we run anim? I would like it to come up at https://joncomo.github.io/anim/ and also if you download it locally you should be able to just click index.html and have it run. Currently I'm getting some resources fail to load.

**Comment by catruge** [comment] 2021-02-28 16:09
Hello @JonComo. I'm sorry that this happened, but it is easy to fix. **TL;DR**, I made the changes that I mentioned in #19 and created a pull request with them (#20). These should fix the workflow and publish the site to the `gh-pages` branch once merged. To double-check that the merge corrected the problem, go to https://github.com/JonComo/anim/actions/workflows/github-pages.yml and look for something that looks similar to this (with the green check mark to the left):
![2021-02-28_09-46](https://user-images.githubusercontent.com/49883288/109423019-f0b9a980-79ab-11eb-85dd-a4e587469966.png)

If you do not see anything like that, then click on <kbd>Run workflow</kbd>:
![2021-02-28_09-46](https://user-images.githubusercontent.com/49883288/109423107-4beb9c00-79ac-11eb-85a3-4d8d456450f0.png)
and then click on the green <kbd>Run workflow</kbd> (make sure that the `master` branch is selected in the drop-down!):
![2021-02-28_09-46](https://user-images.githubusercontent.com/49883288/109423201-9705af00-79ac-11eb-94e9-527b767175ba.png)

Secondly, the GitHub Pages settings must be modified to serve the `gh-pages` branch instead of `master`. To do this, navigate to **Settings > GitHub Pages** and click on the branch drop-down under **Source** Here is a screenshot:
![2021-02-28_09-46](https://user-images.githubusercontent.com/49883288/109422526-e4cce800-79a9-11eb-9fde-9e358a6c1e87.png)

***

Here's the long version:

Right now, the README is shown at https://joncomo.github.io/anim/. Since GitHub Pages only lets you serve the root or `docs/` directories but Webpack builds to `dist/`,  we can't serve the master branch. Instead, the GitHub Actions job I wrote should essentially push the `dist/` directory to a branch called `gh-pages`. The problem is that I wrote the GitHub Actions job for the fork I created. Since forks' default (`master` in this case) branches are supposed to reflect `upstream`'s master branch, I was using another branch for recording and testing my changes. It would've been better to make this change before #19 was merged, so that the site shouldn't stop working for long. I don't want to undo the merge because I don't know exactly what that will do and if it will mess up this repository (I think that it just drops the merged commits, but am not sure). Instead, I created pull request #20 which should fix the the GitHub Actions workflow. When merging, it should trigger the workflow, but if it doesn't, you must run it manually through the GitHub Actions UI. Additionally, the GitHub Pages branch must be set to `gh-pages` to serve the correct content.

The reason that you can't just download the repository and open `dist/index.html` is because of Webpack. The primary purpose of Webpack is to package numerous files into a few large ones. Webpack then stores these large files under the `dist/` directory (this can be configured, if necessary). In the case of anim, only one large file is created (`dist/main.js`). Note that this is different from the `main.js` that existed before setting up Webpack. The original `main.js` is now under `src/`, as `index.js`, with a few modifications so that it would use NPM packages and such. NPM (Node Package Manager; website at https://www.npmjs.com/) is a package manager used for Node.js (a JavaScript runtime for back-ends; website at https://nodejs.org/). NPM can also be used for installing packages for front-end development. This is how we installed Webpack. Of course, this means that you must have Node.js and NPM installed. If you're running Linux, then you would normally just have to install the `nodejs` and `npm` packages (names might differ across distributions). If you are running macOS, you can use a package manager like Homebrew (https://brew.sh/) or directly install Node.js and NPM from https://nodejs.org/en/download/, although you would have to reinstall it every time you want to upgrade it. If you decide to use Homebrew, https://brew.sh/ has installation instructions. Afterwards, you should be able to run `homebrew install node` (instructions at https://nodejs.dev/learn/how-to-install-nodejs). Then, navigate to the repository directory and run `npm install` to install necessary packages. To compile, run `npm run build`. Now, a `main.js` file should appear in the `dist/` directory. If you open `dist/index.html` in your browser, it should work. This is how the GitHub Actions workflow builds the site. Additionally, you can run `npm start` and open your browser up to http://localhost:9000/. You should see anim there. When you make a modification to the code and save, it should reflect to there after a few seconds. Since `src/index.js` is a large file, it will take a bit to compile. This could be fixed by splitting it up into more files. Note that the web page will reload completely. To fix this, we can set something up like hot module replacement (https://webpack.js.org/guides/hot-module-replacement/), but this would still require us to split up the files.

**Comment by catruge** [comment] 2021-03-01 19:03
@JonComo, @SankalpMe, it might be a good idea to update the README so that whoever reads it understands that they must have Node.js and NPM installed to develop `anim`. Additionally, we could use GitHub Releases to allow others to download the compiled code so that using it is similar to how it was before setting up Webpack. What do you think?

**Comment by JonComo** [comment] 2021-03-03 00:45
@catruge I like the idea of github releases so its easy to have a local version without having to build. What's involved in that process? Should we open a new issue for that?

**Comment by catruge** [comment] 2021-03-03 01:00
@JonComo, it should be possible to just click on the <kbd>Releases</kbd> or `Create a new release` on the right of the repository page:
![2021-02-28_09-46](https://user-images.githubusercontent.com/49883288/109735363-a3e2f800-7b90-11eb-8a24-4fcea3a2d7bb.png)
Then, the page can be filled out:
![2021-02-28_09-46](https://user-images.githubusercontent.com/49883288/109735496-db51a480-7b90-11eb-86df-d60fe2384bc5.png)
1. Version. Normally semantic versioning would be used. A semantic version has numbers X.Y.Z where X is the major version, Y is the minor version and Z is the patch version. Z is normally used for backwards-compatible patches, Y is used for backwards-compatible additions and X is for breaking changes. The semantic versioning website is at https://semver.org/.
2. Here, you should choose the `gh-pages` branch because it is already built (you could double-check the Actions tab to make sure it is).
3. Title.
4. Body.
5. Submit.

The version in `package.json` and the one shown in the label on the `anim` interface should also match the version above, so that there's no confusion. It would be a pretty good idea to open an issue to discuss it. GitHub has a page describing releases [here](https://docs.github.com/en/github/administering-a-repository/about-releases), if you wanted to take a look at it.

**Comment by catruge** [comment] 2021-03-04 19:36
Hello. I wanted to mention that we could use the `html-webpack-plugin` package to create `dist/index.html` instead of doing it manually. Additionally, we could include a template file for `dist/index.html`. This would make it possible to clear the build directory to prevent old files from building up inside, but more importantly would allow us to easily move around bundles and would let us add their hashes to their filenames so that browsers will re-download them whenever necessary instead of using cached versions.

**Comment by catruge** [comment] 2021-03-14 22:46
@JonComo, @SankalpMe, should we close this issue, or is there something else that should be discussed?

**Closed** 2021-03-15 09:20 UTC
