### ISSUE TITLE
Index.js code - Modular

### ISSUE THREAD

**Issue by SankalpMe** [JonComo/anim#25] opened 2021-03-01 05:34 UTC
Webpack throws warning that index.js file is a extremely large file, must start splitting the file.

**Comment by catruge** [comment] 2021-03-01 20:03
@SankalpMe, that's a good idea. Do you mind if I work on that with you?

**Comment by SankalpMe** [comment] 2021-03-02 03:00
Sure that will be really great.

**Comment by catruge** [comment] 2021-03-02 13:40
@SankalpMe, since ES6 modules' code is run only on the first import, we could have a file (maybe `src/resources.js` or `src/setup.js`) that sets up Math.JS, gets the canvas context and all that. That way, we wouldn't have to export an initialisation function from every single file that we create; that setup file could be imported into each of them without any implications.

**Comment by catruge** [comment] 2021-03-02 14:01
Also, we should lazy loading wherever possible.

**Comment by catruge** [comment] 2021-03-02 18:05
I created a branch on our fork (https://github.com/supreme-pancakes/anim/tree/resources.js). The branch should split some of the code at the start of `src/index.js` into another file. @SankalpMe, should I create a pull request?

**Comment by JonComo** [comment] 2021-03-03 00:56
I love the idea of splitting the code into separate modules... each focused on a particular subject or topic. As I took courses through college I added functionality (like 3D graphing when taking Calculus 3 for example to some physics things I believe) but put it all in one file. Splitting it up is a great improvement and would make anim much more extendable. Thanks for kicking this off @SankalpMe and @catruge

**Comment by catruge** [comment] 2021-03-03 01:21
@SankalpMe, @JonComo, I think I've finished that `resources.js` file that I was working on. I created pull request #30 with my changes.

**Comment by SankalpMe** [comment] 2021-03-03 04:07
If we are starting the modularity won't it be good to follow a slight restructuring like instead of using `GRID_X`, `GRID_Y` we could have `GRID.X`, `GRID.Y`.

**Comment by catruge** [comment] 2021-03-03 11:43
@SankalpMe, I think that is a good idea. I'll update my `resources.js` pull request so it uses that.

**Comment by catruge** [comment] 2021-03-03 14:07
@JonComo, @SankalpMe, do you think that we could move `t_ease`, `t_steps`, `t_percent` and `t_in_out` to the `Transition` class?

**Comment by SankalpMe** [comment] 2021-03-03 17:33
I guess we should start planing..

**Comment by catruge** [comment] 2021-03-03 19:43
@JonComo, can I separate out the text and image border colour from the palette available to the user? I think that it would make more sense because then it could be called `border` instead of `gray`.

**Comment by JonComo** [comment] 2021-03-03 20:28
@catruge sounds good to me!

**Comment by JonComo** [comment] 2021-03-03 20:31
I think the biggest splitting would occur by subject. So functions for 2D graphing could go in a 2dgraphing.js file, 3D graphing in a 3dgraphing.js file... vector calculus stuff in a vectorcalc.js file, etc. 

Currently we have math.import({ ... }) with all these functions pertaining to different subjects all jumbled together. Is there a way we could instead make a file like vectorcalc.js, require it in the main source file, and by doing so it would add all its functions to math.js?

**Comment by catruge** [comment] 2021-03-03 22:30
@JonComo, yeah, that would be possible, and would be really easy to do since JavaScript supports object destructuring, so all those functions could be separated into multiple object literals, each in a separate file, and then could all be imported, then the code
```
math.import({
  ...firstImport, // These are real dots; they're not an ellipsis!
  ...secondImport,
  ...thirdImport,
});
```
would put them together. The problem is that no error or warning appears to result when more than one property is used, making it hard to check for duplicates. Another option is `Object.assign()`, but it doesn't pose any advantage (and object destructuring might just be easier to read). I also checked if ESLint will look for duplicates and it doesn't. A solution would be to write a function that checks for duplicates to prevent mysterious bugs. The `src/resources.js` file could be imported into each file (for example, the `vectorcalc.js` that you mentioned) so that all those files could have access to the canvas and so on, if necessary.

**Comment by catruge** [comment] 2021-03-06 22:57
Hello @JonComo and @SankalpMe. I started working on splitting up the classes defined in `src/index.js` into separate files (#38).

**Comment by JonComo** [comment] 2021-04-21 05:09
@catruge Nice job! Closing this.

**Closed by JonComo** 2021-04-21 05:09 UTC
